---
title: "USGS North American Breeding Bird Survey Data (1966-2019) for Illinois "
author: Alec Luro and Andrew Braxton
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source_code: embed
    theme: paper
    logo: illinois_logo_48x48px.png
runtime: shiny
---

```{r setup, include=FALSE}
# Load packages -------------------------------------------------------------
library(flexdashboard)
library(shiny)
library(data.table)
library(dtplyr)
library(dplyr)
library(magrittr)
library(stringr)
library(ggplot2)
library(hrbrthemes)
library(tidyr)

# Import data and subset Illinois data -------------------------------------------------------------
full_ill_data <-
  readRDS("../data/complete_bbs_data.rds") %>%
  lazy_dt %>% 
  filter(State == "ILLINOIS" & RunType == 1) %>% 
  na.omit

# Get number of unique routes completed per year
routes_per_survey_year <-
  full_ill_data %>%
  group_by(Year) %>%
  summarise(
    routes_per_year = length(unique((RouteDataID))
    )) %>%
  as_tibble()

# Add survey counts weighted by number of routes completed for given year
illinois_data <-
  full_ill_data %>%
  group_by(Year, English_Common_Name, Family) %>%
  summarise(
    total_birds = sum(SpeciesTotal)
  ) %>%
  as_tibble() %>% 
  inner_join(.,
             routes_per_survey_year,
             by = "Year") %>% 
  mutate(weighted_total_birds = (total_birds/routes_per_year))

# List of all species surveyed in Illinois
species_list <-
  illinois_data %>% 
  distinct(English_Common_Name) %>% 
  # drop unidentified birds
  filter(!startsWith(English_Common_Name, "unid.")) %>% 
  # remove aliases for cleaner sorting
  mutate(English_Common_Name = str_replace(English_Common_Name, " ?\\(.*\\) ?", "")) %>%
  arrange(English_Common_Name) %>% 
  pull(English_Common_Name)

# List of all families surveyed in Illinois
family_list <-
  full_ill_data %>% 
    pull(Family) %>%  
    unique() %>% 
    sort()

# List of all unique routes in Illinois
route_list <-
  full_ill_data %>% 
  pull(RouteName) %>% 
  unique() %>% 
  sort()
```

Bird survey trends
===================================== 

Column {.sidebar}
-----------------------------------------------------------------------
<br>

```{r species_survey_input}
# Allow choice of Family or individual species
selectInput("taxonomic_level", label = "Taxon",
            c(Family = "choice_family", Species = "choice_species"))

# Species choice (if Taxon == Species)
conditionalPanel(
  condition = "input.taxonomic_level == 'choice_species'",
  selectInput("species", label = "Species",
            choices = c("All species", species_list))
)

# Family choice (if Taxon == Family)
conditionalPanel(
  condition = "input.taxonomic_level == 'choice_family'",
  selectInput("family", label = "Family",
            choices = family_list)
)

# Choice for survey year range
sliderInput("time_range", label = "Years:",
            min = 1966, max = 2019, value = c(1966,2019),
            sep = "")
```

Column {data-width=200}
-----------------------------------------------------------------------
### [List of Illinois Endangered and Threatened Species](https://www2.illinois.gov/dnr/ESPB/Documents/ET%20List%20Review%20and%20Revision/Illinois%20Endangered%20and%20Threatened%20Species.pdf)
```{r endangered_species}

illinois_endangered <-
  tibble(Status = c(
    rep("Endangered", 23),
    rep("Threatened", 6)),
         Species = c(
           "Short-eared Owl",
           "Upland Sandpiper",
           "American Bittern",
           "Swainson's Hawk",
           "Piping Plover",
           "Black Tern",
           "Northern Harrier",
           "Little Blue Heron",
           "Snowy Egret",
           "Common Gallinule",
           "Loggerhead Shrike",
           "Black Rail",
           "Swainson's Warbler",
           "Yellow-crowned Night Heron",
           "Black-crowned Night Heron",
           "Wilson's Phalarope",
           "King Rail",
           "Forster's Tern",
           "Common Tern",
           "Least Tern",
           "Bewick's Wren",
           "Greater Prairie-Chicken",
           "Yellow-headed Blackbird",
           "Chuck-will's-widow",
           "Rufa Red Knot",
           "Black-billed Cuckoo",
           "Least Bittern",
           "Osprey",
           "Cerulean Warbler"
         )) %>% 
  arrange(Species)

DT::renderDataTable({
  illinois_endangered
})

```



Column
-----------------------------------------------------------------------

### Species plot
```{r plot_species}

# Reactive function to subset data by Taxon (species or family) inputs
plot_data <-
  reactive({
    # If selected Taxon == Species and input for species is not "All", filter data by selected single species
    if(input$taxonomic_level == "choice_species"){
      {if (!input$species == "All species") filter(illinois_data, English_Common_Name == input$species) else illinois_data} 
    } else {
      # If selected Taxon ==  Family, filter data by selected family
       filter(illinois_data, Family == input$family)
    }
  })

# Reactive function to select plot title name input by Taxon inputs
plot_title <-
  reactive({
    if(input$taxonomic_level == "choice_species"){input$species} else {input$family}
  })

# Make survey data plot
renderPlot(
  {
  plot_data() %>% 
  # get data for single species
  filter(Year %in% input$time_range[1]:input$time_range[2]) %>%
  group_by(Year) %>%
  summarise("Total Birds Counted per Routes Surveyed" = sum(weighted_total_birds)) %>%
  ungroup() %>%
ggplot(
  .,
  aes(
    x = Year,
    y = `Total Birds Counted per Routes Surveyed`
  )
) +
ggtitle(
  paste(
    plot_title(),
    "surveyed relative population sizes in Illinois from",
    input$time_range[1],
    "to",
    input$time_range[2],
    sep = " ")) +
  geom_point() +
  geom_smooth() +
  scale_x_continuous(breaks = seq(1960, 2020, 5)) +
  hrbrthemes::theme_ipsum_ps(
    plot_title_size = 18,
    axis_text_size = 14,
    axis_title_size = 18
  )
    
  })

```

Species Sightings by Route
===================================== 

Column {.sidebar}
-----------------------------------------------------------------------

### Species and Year

```{r sidebar_routes}

selectInput("species2", label = "Species", choices = species_list,
            selected = "American Robin")
#sliderInput("year2", label = "Year", min = 1966, max = 2019, value = 2019, sep = "")
selectInput("routes", label = "Route", choices = route_list, multiple = TRUE, selectize = TRUE,
            selected = route_list[1:10])

```

Column
-----------------------------------------------------------------------

### Bird Sightings by Route (from 2009-2019)

```{r plot_route_data}

# Set up route data before plotting
route_data <-
  reactive({
    full_ill_data %>% 
    filter(English_Common_Name == input$species2) %>% 
    filter(Year %in% 2009:2019) %>% 
    filter(RouteName %in% input$routes) %>% 
    mutate(RouteName = as.factor(RouteName)) %>%
    select(RouteName, Sightings = SpeciesTotal, Year) %>% 
    as_tibble
  })

# Plot birds counted by route, filled by # sightings and in descending order by year
renderPlot({
  route_data() %>% 
    ggplot(mapping = aes(x = reorder(RouteName, -Sightings), y = Sightings, fill = Sightings, group = reorder(Year, -Year))) +
    geom_col() +
    scale_fill_gradient(low = "red", high = "green") +
    geom_text(aes(label = Year), position = position_stack(vjust = 0.5)) +
    xlab("Route Location") +
    ylab("Total Sightings") +
    theme(axis.text.x = element_text(angle = 45, hjust = 1))
})
```
