---
title: "USGS North American Breeding Bird Survey Data (1966-2019)"
author: Alec Luro
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source_code: embed
    theme: paper
    #logo: illinois_logo_48x48px.png
runtime: shiny
---

```{r packages, include=FALSE}
# Load packages -------------------------------------------------------------
library(flexdashboard)
library(shiny)
library(data.table)
library(dtplyr)
library(dplyr)
library(magrittr)
library(stringr)
library(ggplot2)
library(hrbrthemes)
library(tidyr)

```

Bird survey trends
===================================== 

Column {.sidebar}
-----------------------------------------------------------------------
<br>

```{r input_state_survey_subset}

# Choice of all U.S. or individual state
# States Surveyed
states <-
  c("All States", "ALABAMA", "ALASKA", "ARIZONA", "ARKANSAS", "CALIFORNIA", "COLORADO", 
"CONNECTICUT", "DELAWARE", "FLORIDA", "GEORGIA", "IDAHO", "ILLINOIS", 
"INDIANA", "IOWA", "KANSAS", "KENTUCKY", "LOUISIANA", "MAINE", 
"MARYLAND", "MASSACHUSETTS", "MICHIGAN", "MINNESOTA", "MISSISSIPPI", 
"MISSOURI", "MONTANA", "NORTH CAROLINA", "NORTH DAKOTA", "NEBRASKA", 
"NEVADA", "NEW HAMPSHIRE", "NEW JERSEY", "NEW MEXICO", "NEW YORK", 
"OHIO", "OKLAHOMA", "OREGON", "PENNSYLVANIA", "RHODE ISLAND", 
"SOUTH CAROLINA", "SOUTH DAKOTA", "TENNESSEE", "TEXAS", "UTAH", 
"VERMONT", "VIRGINIA", "WEST VIRGINIA", "WASHINGTON", "WISCONSIN", 
"WYOMING")

selectInput("state_choice", label = "State",
            choices =  states,
            selected = "All States")

```

```{r survey_data, include=FALSE}


# Import data and subset Illinois data -------------------------------------------------------------
full_data <-
    readRDS("data/complete_bbs_data.rds") %>%
    lazy_dt %>%
    filter(CountryNum == 840,
           RunType == 1) %>% 
    na.omit


# Get number of unique routes completed per year
routes_per_survey_year <-
  full_data %>%
  group_by(Year) %>%
  summarise(
    routes_per_year = length(unique((RouteDataID))
    )) %>%
  as_tibble() 

# Add survey counts weighted by number of routes completed for given year
full_data <-
  full_data %>%
  group_by(Year, English_Common_Name, Family) %>%
  summarise(
    total_birds = sum(SpeciesTotal)
  ) %>%
  as_tibble() %>% 
  inner_join(.,
             routes_per_survey_year,
             by = "Year") %>% 
  mutate(weighted_total_birds = (total_birds/routes_per_year))

# List of all species surveyed 
species_list <-
  full_data %>% 
  distinct(English_Common_Name) %>% 
  # drop unidentified birds
  filter(!str_detect(English_Common_Name, "(?i)unid"),
         !str_detect(English_Common_Name, "(?i)hybrid")) %>% 
  # remove aliases for cleaner sorting
  mutate(English_Common_Name = str_replace(English_Common_Name, " ?\\(.*\\) ?", "")) %>%
  arrange(English_Common_Name) %>% 
  pull(English_Common_Name)

# List of all families surveyed 
family_list <-
  full_data %>% 
    pull(Family) %>%  
    unique() %>% 
    sort()

```

```{r input_survey_data_subset}

# Allow choice of Family or individual species
selectInput("taxonomic_level", label = "Taxon",
            c(Family = "choice_family", Species = "choice_species"))

# Species choice (if Taxon == Species)
conditionalPanel(
  condition = "input.taxonomic_level == 'choice_species'",
  selectInput("species", label = "Species",
            choices = c("All species", species_list))
)

# Family choice (if Taxon == Family)
conditionalPanel(
  condition = "input.taxonomic_level == 'choice_family'",
  selectInput("family", label = "Family",
            choices = family_list)
)

# Choice for survey year range
sliderInput("time_range", label = "Years:",
            min = 1966, max = 2019, value = c(1966,2019),
            sep = "")
```


Column {data-width=200}
-----------------------------------------------------------------------
### [List of Illinois Endangered and Threatened Species](https://www2.illinois.gov/dnr/ESPB/Documents/ET%20List%20Review%20and%20Revision/Illinois%20Endangered%20and%20Threatened%20Species.pdf)
```{r endangered_species}

illinois_endangered <-
  tibble(Status = c(
    rep("Endangered", 23),
    rep("Threatened", 6)),
         Species = c(
           "Short-eared Owl",
           "Upland Sandpiper",
           "American Bittern",
           "Swainson's Hawk",
           "Piping Plover",
           "Black Tern",
           "Northern Harrier",
           "Little Blue Heron",
           "Snowy Egret",
           "Common Gallinule",
           "Loggerhead Shrike",
           "Black Rail",
           "Swainson's Warbler",
           "Yellow-crowned Night Heron",
           "Black-crowned Night Heron",
           "Wilson's Phalarope",
           "King Rail",
           "Forster's Tern",
           "Common Tern",
           "Least Tern",
           "Bewick's Wren",
           "Greater Prairie-Chicken",
           "Yellow-headed Blackbird",
           "Chuck-will's-widow",
           "Rufa Red Knot",
           "Black-billed Cuckoo",
           "Least Bittern",
           "Osprey",
           "Cerulean Warbler"
         )) %>% 
  arrange(Species)

DT::renderDataTable({
  illinois_endangered
})

```



Column
-----------------------------------------------------------------------

### Species plot
```{r plot_species}

# Reactive function to subset data by Taxon (species or family) inputs
plot_data <-
  reactive({
    # If selected Taxon == Species and input for species is not "All", filter data by selected single species
    if(input$taxonomic_level == "choice_species"){
      {if (!input$species == "All species") filter(full_data, English_Common_Name == input$species) else full_data} 
    } else {
      # If selected Taxon ==  Family, filter data by selected family
       filter(full_data, Family == input$family)
    }
  })

# Reactive function to select plot title name input by Taxon inputs
plot_title <-
  reactive({
    if(input$taxonomic_level == "choice_species"){input$species} else {input$family}
  })

# Make survey data plot
renderPlot(
  {
  plot_data() %>% 
  # get data for single species
  filter(Year %in% input$time_range[1]:input$time_range[2]) %>%
  group_by(Year) %>%
  summarise("Total Birds Counted per Routes Surveyed" = sum(weighted_total_birds)) %>%
  ungroup() %>%
ggplot(
  .,
  aes(
    x = Year,
    y = `Total Birds Counted per Routes Surveyed`
  )
) +
ggtitle(
  paste(
    plot_title(),
    "surveyed relative population sizes  from",
    input$time_range[1],
    "to",
    input$time_range[2],
    sep = " ")) +
  geom_point() +
  geom_smooth() +
  scale_x_continuous(breaks = seq(1960, 2020, 5)) +
  hrbrthemes::theme_ipsum_ps(
    plot_title_size = 18,
    axis_text_size = 14,
    axis_title_size = 18
  )
    
  })

```
