name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.9.9 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "us-breeding-bird-survey" #Must be unique in Heroku
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          healthcheck: "https://us-breeding-bird-survey.herokuapp.com/"
          usedocker: true
          delay: 60
          rollbackonhealthcheckfailed: true
        env:
          HD_API_KEY: ${{secrets.MAPS_API_KEY}}